import Data.Array

data Alignment = Match | GapA | GapB deriving (Show, Eq, Ord)

similarity a b
  | a == b    = 1
  | otherwise = 0

gap = -1

nw x' y' = let b = bt lx ly in (reverse $ fst b, reverse $ snd b) where
  (lx, ly) = (length x', length y')
  ( x,  y) = (listArray (1, lx) x', listArray (1, ly) y')
  a = listArray bounds [f i j | (i, j) <- range bounds]
  bounds = ((0, 0), (lx, ly)) 
  f 0 j = (-j, GapA)
  f i 0 = (-i, GapB)
  f i j = maximum [ (fst (a ! (i-1, j-1)) + similarity (x!i) (y!j), Match)
                  , (fst (a ! (i-1, j-0)) + gap, GapB)
                  , (fst (a ! (i-0, j-1)) + gap, GapA) ]
  bt 0 0 = ("", "") -- backtracking 
  bt i j = case a ! (i, j) of
    (_, Match) -> let (px, py) = bt (i-1) (j-1) in ((x!i):px, (y!j):py)
    (_, GapA)  -> let (px, py) = bt (i-0) (j-1) in (  '-':px, (y!j):py)
    (_, GapB)  -> let (px, py) = bt (i-1) (j-0) in ((x!i):px,   '-':py)

-- compare insulin

test = nw "AGCCCTCCAGGACAGGCTGCATCAGAAGAGGCCATCAAGCAGGTCTGTTCCAAGGGCCTTTGCGTCAGATCACTGTCCTTCTGCCATGGCCCTGTGGATGCGCCTCCTGCCCCTGCTGGCGCTGCTGGCCCTCTGGGGACCTGACCCAGCCGCAGCCTTTGTGAACCAACACCTGTGCGGCTCACACCTGGTGGAAGCTCTCTACCTAGTGTGCGGGGAACGAGGCTTCTTCTACACACCCAAGACCCGCCGGGAGGCAGAGGACCTGCAGGTGGGGCAGGTGGAGCTGGGCGGGGGCCCTGGTGCAGGCAGCCTGCAGCCCTTGGCCCTGGAGGGGTCCCTGCAGAAGCGTGGCATTGTGGAACAATGCTGTACCAGCATCTGCTCCCTCTACCAGCTGGAGAACTACTGCAACTAGACGCAGCCCGCAGGCAGCCCCACACCCGCCGCCTCCTGCACCGAGAGAGATGGAATAAAGCCCTTGAACCAGCAAAA" "AGCCCTCCAGGACAGGCTGCATCAGAAGAGGCCATCAAGCAGATCACTGTCCTTCTGCCATGGCCCTGTGGATGCGCCTCCTGCCCCTGCTGGCGCTGCTGGCCCTCTGGGGACCTGACCCAGCCGCAGCCTTTGTGAACCAACACCTGTGCGGCTCACACCTGGTGGAAGCTCTCTACCTAGTGTGCGGGGAACGAGGCTTCTTCTACACACCCAAGACCCGCCGGGAGGCAGAGGACCTGCAGGTGGGGCAGGTGGAGCTGGGCGGGGGCCCTGGTGCAGGCAGCCTGCAGCCCTTGGCCCTGGAGGGGTCCCTGCAGAAGCGTGGCATTGTGGAACAATGCTGTACCAGCATCTGCTCCCTCTACCAGCTGGAGAACTACTGCAACTAGACGCAGCCCGCAGGCAGCCCCACACCCGCCGCCTCCTGCACCGAGAGAGATGGAATAAAGCCCTTGAACCAGCAAAA"
